FROM ubuntu:14.04

# wget needs to be first as it's used below
RUN apt-get install -qq -y wget git

# Download dependencies.  Do this early to take advantage of docker caching as changes are made
RUN wget --directory-prefix=/root --quiet --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u51-b16/jdk-8u51-linux-x64.tar.gz
RUN wget --directory-prefix=/root --quiet --no-check-certificate http://apache.mirror.rafal.ca//ant/binaries/apache-ant-1.9.6-bin.tar.gz
RUN wget --directory-prefix=/root --quiet --no-check-certificate http://download-aws.ej-technologies.com/install4j/install4j_linux_6_0_3.deb

# JAVA
RUN mkdir /opt/jdk
RUN tar -zxf /root/jdk-8u51-linux-x64.tar.gz -C /opt/jdk
RUN update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_51/bin/java 100
RUN update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_51/bin/javac 100
RUN update-alternatives --display java
RUN update-alternatives --display javac
RUN java -version
RUN rm /root/jdk-8u51-linux-x64.tar.gz

# ANT
RUN tar -zxf /root/apache-ant-1.9.6-bin.tar.gz -C /usr/local
RUN rm /root/apache-ant-1.9.6-bin.tar.gz
RUN wget --directory-prefix=/root --quiet --no-check-certificate http://downloads.sourceforge.net/project/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3-bin.tar.bz2
RUN tar -jxf /root/ant-contrib-1.0b3-bin.tar.bz2 -C /root
RUN mv /root/ant-contrib/ant-contrib-1.0b3.jar /usr/local/apache-ant-1.9.6/lib
RUN rm /root/ant-contrib-1.0b3-bin.tar.bz2

# INSTALL4J
RUN dpkg -i /root/install4j_linux_6_0_3.deb
# NOTE:  chmoding for world write is temporary until I dig into the reason for writing to the install4j home.
RUN chmod a+w /opt/install4j6/jres
RUN rm /root/install4j_linux_6_0_3.deb

# PERFORCE CLIENT
RUN wget --directory-prefix=/usr/local/bin --quiet --no-check-certificate http://www.perforce.com/downloads/perforce/r15.1/bin.linux26x86_64/p4
RUN chmod 755 /usr/local/bin/p4

# Installation of dependencies is complete so switch to a non-priviledged user for the rest.
RUN useradd -ms /bin/bash bobthebuilder
USER bobthebuilder
WORKDIR /home/bobthebuilder
#TODO:  Use the corporate license for install4j
RUN install4jc -L E-M6-J_M#816838-2015.11.10-90-y6itbuaydfr5n9#9bb8
# install4jc -L FLOAT:10.52.114.115

# Sync the latest content into the workspace
RUN echo "AutoUser@p4v" | /usr/local/bin/p4 -p 10.52.114.110:1667 -u autouser -c AutoUser_DSM_Build_Linux_jenkins--1413832970 login
RUN mkdir -p /home/bobthebuilder/p4/dsmbuild
RUN echo "AutoUser@p4v" | /usr/local/bin/p4 -p 10.52.114.110:1667 -u autouser -c AutoUser_DSM_Build_Linux_jenkins--1413832970 sync -f
RUN echo "#!/bin/sh -x" > /home/bobthebuilder/build.sh
RUN echo "echo 'AutoUser@p4v' |/usr/local/bin/p4 -p 10.52.114.110:1667 -u autouser -c AutoUser_DSM_Build_Linux_jenkins--1413832970 sync" >> /home/bobthebuilder/build.sh
RUN echo "/usr/local/apache-ant-1.9.6/bin/ant -verbose -logger org.apache.tools.ant.listener.ProfileLogger -f build.xml main-notests" >> /home/bobthebuilder/build.sh
RUN chmod 755 /home/bobthebuilder/build.sh
WORKDIR /home/bobthebuilder/p4/dsmbuild/src/Manager/Installer
#CMD /home/bobthebuilder/build.sh
